'use client'
import { motion } from "framer-motion";

export default function GlobalPage() {
  return (
    <main className="min-h-screen bg-[#e9fdf7] text-neutral-900">
      <section className="mx-auto flex max-w-4xl flex-col gap-10 px-4 py-12 sm:px-6 lg:py-16">

        {/* 페이지 헤더 */}
        <header className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-700">
            Exhibit 4 – Global Connections
          </p>
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl text-neutral-900">
            Global Impacts of the Industrial Revolution
          </h1>
          <p className="text-sm text-neutral-700">
            Compelling Question: Was the Industrial Revolution truly a turning point for humanity,
            or just another stage of inequality and exploitation?
          </p>
        </header>

        {/* Mini-Argument */}
        <section className="rounded-2xl border border-teal-200 bg-white p-6 sm:p-7 shadow-sm">
          <h2 className="mb-3 text-lg font-semibold text-teal-700">Mini-Argument</h2>
          <p className="text-sm leading-relaxed text-neutral-800">
            Industrialization spread throughout the railroads and transportation, which transmitted
            the influence toward other countries, globally (OER project, 2024). Globally, it
            influenced population density to be increased in cities from the rural areas. In the
            pre-Industrial period, over 80 percent of people inhabited rural areas. However, in the
            early 1900s, the majority of the population in England and the United States went to the
            city, indicating decent influence globally (Impact of Industrial Revolution, n.d.).
            Therefore, I assume that Industrialization had a positive effect on the whole world by
            spreading transportation.
          </p>
        </section>

        {/* Artifact 1 */}
        <section className="space-y-4 rounded-2xl border border-teal-200 bg-white p-6 sm:p-7 shadow-sm">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-600">
              Artifact 1
            </p>
            <h2 className="text-lg font-semibold text-neutral-900">
              Charles Babbage&apos;s Analytical Engine (1871)
            </h2>
          </header>

          {/* 이미지 */}
          <div className="overflow-hidden rounded-xl border border-neutral-200 bg-neutral-100">
            <img
              src="https://media.gettyimages.com/id/90739744/photo/charles-babbages-analytical-engine-1871.jpg?s=1024x1024&w=gi&k=20&c=OdrZw1ZOkHnPsZ5xZPh88337hVFPN-OsfEFqev8jt58="
              alt="Babbage Analytical Engine"
              className="w-full h-auto object-cover"
            />
          </div>

          {/* 설명 */}
          <div className="space-y-2 text-sm leading-relaxed">
            <p className="text-neutral-800">
              The following picture depicts an analytical engine generated by Charles Babbage. This
              invention is significant because it played a role as a foundation of the computer
              model. Last but not least, the visual content depicts how industrialization assisted
              global aspects which were advantageous.
            </p>
            <p className="text-xs italic text-neutral-500">
              Caption: Babbage&apos;s analytical engine shows how industrial innovations in Britain
              helped shape the foundations of modern computing, which later spread globally.
            </p>
          </div>
        </section>

        {/* Artifact 2 */}
        <section className="space-y-4 rounded-2xl border border-teal-200 bg-white p-6 sm:p-7 shadow-sm">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-600">
              Artifact 2
            </p>
            <h2 className="text-lg font-semibold text-neutral-900">
              Report on the Sanitary Conditions of the Labouring Population of Great Britain (1842)
            </h2>
          </header>

          <p className="text-sm leading-relaxed text-neutral-800">
            The following source depicts the working severity regarding the labor at the period of
            Industrialization. Not only is the excerpt informing about the danger and seriousness of
            the circumstances, the following also complicates this source by having negative facets
            or aspects during the Industrialization as a global influence.
          </p>

          {/* 원문 박스 */}
          <div className="max-h-72 overflow-y-auto rounded-xl border border-neutral-200 bg-neutral-50 p-4">
            <p className="whitespace-pre-line text-[12px] leading-relaxed text-neutral-700">
              {`First, as to the extent and operation of the evils which are the subject of this inquiry:-That the various forms of epidemic, endemic, and other disease caused, or aggravated, or propagated chiefly amongst the labouring classes by atmospheric impurities produced by decomposing animal and vegetable substances, by damp and filth, and close and overcrowded dwellings prevail amongst the population... (Report on the Sanitary Conditions of the Labouring Population of Great Britain, 1842)`}
            </p>
          </div>

          <p className="text-xs italic leading-relaxed text-neutral-500">
            Caption: This sanitary report describes how industrial urban environments were filled
            with filth, overcrowding, and disease—complicating the positive story of
            industrialization.
          </p>
        </section>

        {/* Data Display */}
        <section className="space-y-4 rounded-2xl border border-teal-200 bg-white p-6 sm:p-7 shadow-sm">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-600">
              Data Display
            </p>
            <h2 className="text-lg font-semibold text-neutral-900">
              Historical Carbon Dioxide Emissions (1750–2023)
            </h2>
          </header>

          <div className="overflow-hidden rounded-xl border border-neutral-200 bg-neutral-50">
            <img
              src="https://www.statista.com/graphic/1/264699/worldwide-co2-emissions.jpg"
              alt="CO2 Emissions Graph"
              className="w-full h-auto object-cover"
            />
          </div>

          <p className="text-sm leading-relaxed text-neutral-800">
            The following graph about carbon dioxide emissions from global fossil fuel combustion
            and industrial processes during 1750–2023 indicates a gradual increase of carbon dioxide
            emissions within the Industrialization period. Furthermore, the visualization complicates
            the claim by showing negative global influences.
          </p>

          <p className="text-xs italic text-neutral-500">
            Caption: Rising CO₂ emissions show that global industrialization created long-term
            environmental costs, challenging the idea that industrial progress was purely positive.
          </p>
        </section>

        {/* Closing Page */}
        <section className="rounded-2xl border border-teal-200 bg-white p-6 sm:p-7 shadow-sm">
          <h2 className="mb-3 text-lg font-semibold text-neutral-900">Page Close</h2>
          <p className="text-sm leading-relaxed text-neutral-800">
            The following had an universal influence with positivity and negativity. However, since
            Industrialization offered uncountable amount of growth in technology and
            social-associated aspects, the incident rather contributed to the positive aspects of
            the entire world.
          </p>
        </section>

      </section>
    </main>
  );
}
