"use client";
import { motion } from "framer-motion";

export default function GlobalPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-50">
      <section className="mx-auto flex max-w-4xl flex-col gap-10 px-4 py-12 sm:px-6 lg:py-16">
        {/* 페이지 헤더 */}
        <header className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-300/80">
            Exhibit 4 – Global Connections
          </p>
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
            Global Impacts of the Industrial Revolution
          </h1>
          <p className="text-sm text-slate-400">
            Compelling Question: Was the Industrial Revolution truly a turning point for humanity,
            or just another stage of inequality and exploitation?
          </p>
        </header>

        {/* Mini-Argument */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-7">
          <h2 className="mb-3 text-lg font-semibold text-emerald-300">Mini-Argument</h2>
          <p className="text-sm leading-relaxed text-slate-100">
            Industrialization spread throughout the railroads and transportation, which transmitted
            the influence toward other countries, globally (OER project, 2024). Globally, it
            influenced population density to be increased in cities from the rural areas. In the
            pre-Industrial period, over 80 percent of people inhabited rural areas. However, in the
            early 1900s, the majority of the population in England and the United States went to the
            city, indicating decent influence globally (Impact of Industrial Revolution, n.d.).
            Therefore, I assume that Industrialization had a positive effect on the whole world by
            spreading transportation.
          </p>
        </section>

        {/* Artifact 1 – Babbage */}
        <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-7">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-sky-300/80">
              Artifact 1
            </p>
            <h2 className="text-lg font-semibold">
              Charles Babbage&apos;s Analytical Engine (1871)
            </h2>
          </header>

          {/* 이미지 자리 – 나중에 실제 이미지로 교체 */}
          <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-950/80">
            <div className="flex aspect-video items-center justify-center text-xs text-slate-500">
              {/* 예: <img src="/images/babbage-analytical-engine.jpg" alt="Charles Babbage's analytical engine" className="h-full w-full object-cover" /> */}
              <img src="https://media.gettyimages.com/id/90739744/photo/charles-babbages-analytical-engine-1871.jpg?s=1024x1024&w=gi&k=20&c=OdrZw1ZOkHnPsZ5xZPh88337hVFPN-OsfEFqev8jt58="></img>
            </div>
          </div>

          {/* 캡션 & 설명 */}
          <div className="space-y-2 text-sm leading-relaxed">
            <p className="text-slate-100">
              The following picture depicts an analytical engine generated by Charles Babbage. This
              invention is significant because it played a role as a foundation of the computer
              model. Last but not least, the visual content depicts how industrialization assisted
              global aspects which were advantageous.
            </p>
            <p className="text-xs italic text-slate-400">
              Caption: Babbage&apos;s analytical engine shows how industrial innovations in Britain
              helped shape the foundations of modern computing, which later spread globally.
            </p>
          </div>
        </section>

        {/* Artifact 2 – Sanitary Report */}
        <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-7">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-sky-300/80">
              Artifact 2
            </p>
            <h2 className="text-lg font-semibold">
              Report on the Sanitary Conditions of the Labouring Population of Great Britain (1842)
            </h2>
          </header>

          {/* 요약 문단 */}
          <p className="text-sm leading-relaxed text-slate-100">
            The following source depicts the working severity regarding the labor at the period of
            Industrialization. Not only is the excerpt informing about the danger and seriousness of
            the circumstances, the following also complicates this source by having negative facets
            or aspects during the Industrialization as a global influence.
          </p>

          {/* 원문 – 스크롤 가능한 박스 */}
          <div className="max-h-72 overflow-y-auto rounded-xl border border-slate-800 bg-slate-950/80 p-4">
            <p className="whitespace-pre-line text-[12px] leading-relaxed text-slate-200">
              {`First, as to the extent and operation of the evils which are the subject of this inquiry:-That the various forms of epidemic, endemic, and other disease caused, or aggravated, or propagated chiefly amongst the labouring classes by atmospheric impurities produced by decomposing animal and vegetable substances, by damp and filth, and close and overcrowded dwellings prevail amongst the population in every part of the kingdom, whether dwelling in separate houses, in rural villages, in small towns, in the larger towns - as they have been found to prevail in the lowest districts of the metropolis.That such disease, wherever its attacks are frequent, is always found in connexion with the physical circumstances above specified, and that where those circumstances are removed by drainage, proper cleansing, better ventilation, and other means of diminishing atmospheric impurity, the frequency and intensity of such disease is abated; and where the removal of the noxious agencies appears to be complete, such disease almost entirely disappears. That high prosperity in respect to employment and wages, and various and abundant food, have afforded to the labouring classes no exemptions from attacks of epidemic disease, which have been as frequent and as fatal in periods of commercial and manufacturing prosperity as in any others. That the formation of all habits of cleanliness is obstructed by defective supplies of water. That the annual loss of life from filth and bad ventilation are greater than the loss from death or wounds in any wars in which the country has been engaged in modern times. That of the 43,000 cases of widowhood, and 112,000 cases of destitute orphanage relieved from the poor rates in England and Wales alone, it appears that the greatest proportion of deaths of the heads of families occurred from the above specified and other removable causes; that their ages were under 45 years; that is to say, 13 years below the natural probabilities of life as shown by the experience of the whole population of Sweden.
(Report on the Sanitary Conditions of the Labouring Population of Great Britain, 1842)`}
            </p>
          </div>

          {/* 캡션 */}
          <p className="text-xs italic leading-relaxed text-slate-400">
            Caption: This sanitary report describes how industrial urban environments were filled
            with filth, overcrowding, and disease. It complicates the positive story of
            industrialization by highlighting the severe health costs faced by labouring people.
          </p>
        </section>

        {/* Data Display */}
        <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-7">
          <header className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-indigo-300/80">
              Data Display
            </p>
            <h2 className="text-lg font-semibold">
              Historical Carbon Dioxide Emissions from Global Fossil Fuel Combustion and Industrial
              Processes (1750–2023)
            </h2>
          </header>

          {/* 그래프 이미지 자리 */}
          <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-950/80">
            <div className="flex aspect-video items-center justify-center text-xs text-slate-500">
              
              {/* 'Add CO₂ emissions graph image here' 대신 삽입된 코드 */}
              {/* 이미지와 텍스트를 묶어 중앙 정렬합니다. */}
              <div className="w-full max-w-lg p-4"> {/* 콘텐츠 영역 확보 (max-w-lg와 p-4는 예시) */}
                
                <a 
                  href="https://www.statista.com/statistics/264699/worldwide-co2-emissions/" 
                  rel="nofollow"
                  target="_blank" // 외부 링크는 새 탭으로 여는 것을 권장
                >
                  <img
                    src="https://www.statista.com/graphic/1/264699/worldwide-co2-emissions.jpg"
                    alt="Statistic: Historical carbon dioxide emissions from global fossil fuel combustion and industrial processes in selected years from 1750 to 2023 (in billion metric tons) | Statista"
                    style={{
                      width: '100%',
                      height: 'auto', // !important는 JSX 인라인 스타일에서 지원 안 됨
                      maxWidth: '1000px',
                      display: 'block', // <a> 태그 안의 <img> 여백 제거
                      margin: '0 auto', // 중앙 정렬
                    }}
                  />
                </a>
                
                <br /> {/* <br> 태그는 항상 />로 닫아줍니다. */}
                
                {/* 텍스트. 부모의 text-xs text-slate-500 스타일이 적용됩니다. */}
                <span className="block text-center"> {/* 텍스트도 중앙 정렬 */}
                  Historical carbon dioxide emissions from 1750 to 2023, {' '}
                  <a 
                    href="https://www.statista.com" 
                    rel="nofollow" 
                    target="_blank"
                    className="text-blue-400 hover:underline" // 가독성을 위해 링크 스타일 추가
                  >
                    Statista
                  </a>
                </span>
              </div>

              {/* 예: <img src="/images/global-co2-1750-2023.png" alt="Historical CO₂ emissions graph" className="h-full w-full object-cover" /> */}
            </div>
          </div>

          {/* 그래프 설명 */}
          <p className="text-sm leading-relaxed text-slate-100">
            The following graph about carbon dioxide emissions from global fossil fuel combustion
            and industrial processes during 1750–2023, indicate a gradual increase of carbon dioxide
            emissions within the Industrialization period. Furthermore, the following visualization
            throughout the graph complicates the following claim by suggesting the negativity of the
            global influence.
          </p>

          <p className="text-xs italic text-slate-400">
            Caption: Rising CO₂ emissions show that global industrialization created long-term
            environmental costs, challenging the idea that industrial progress was purely positive.
          </p>
        </section>

        {/* Closing Page */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-7">
          <h2 className="mb-3 text-lg font-semibold">Page Close</h2>
          <p className="text-sm leading-relaxed text-slate-100">
            The following had an universal influence with positivity and negativity. However, since
            Industrialization offered uncountable amount of growth in technology and
            social-associated aspects, the incident rather contributed to the positive aspects of
            the entire world.
          </p>
        </section>
      </section>
    </main>
  );
}
